### ISSUE TITLE
Querying Transaction table with wrong transaction id throws exception

### ISSUE THREAD

**Issue by JeetenJaiswal** [Impetus/fabric-jdbc-connector#19]
When querying transaction table with transaction id, which does not exists, it throws exception. ideally it should return empty result set instead of throwing exception. 

Exception comes as below.

```
com.impetus.blkch.BlkchnException: Error querying block by hash abcd236db83282f37020778c5e99b6ebc6ce609624ba391e9adc5b72207e39fe

	at com.impetus.fabric.parser.QueryExecutor.getDataNode(QueryExecutor.java:191)
	at com.impetus.fabric.parser.QueryExecutor.getFromTable(QueryExecutor.java:159)
	at com.impetus.fabric.parser.QueryExecutor.executeQuery(QueryExecutor.java:95)
	at com.impetus.fabric.jdbc.FabricStatement.executeQuery(FabricStatement.java:184)
	at com.impetus.fabric.query.QueryBlockIT.testTransactionTableQuery(QueryBlockIT.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.hyperledger.fabric.sdk.exception.ProposalException: queryBlockByHash hash: abcd236db83282f37020778c5e99b6ebc6ce609624ba391e9adc5b72207e39fe peer peer0.org1.example.com channel mychannel error: Unable to query block by hash abcd236db83282f37020778c5e99b6ebc6ce609624ba391e9adc5b72207e39fe 
.... for channel mychannel from peer peer0.org1.example.com 
    with message Sending proposal to peer0.org1.example.com failed because of: gRPC failure=Status{code=UNKNOWN, description=chaincode error (status: 500, message: Failed to get block hash ��#m�2��p w�^�����`�$�9��[r ~9�, error Entry not found in index), cause=null}
	at org.hyperledger.fabric.sdk.Channel.queryBlockByHash(Channel.java:1570)
	at org.hyperledger.fabric.sdk.Channel.queryBlockByHash(Channel.java:1512)
	at com.impetus.fabric.parser.QueryExecutor.getDataNode(QueryExecutor.java:187)
	... 22 more
Caused by: org.hyperledger.fabric.sdk.exception.PeerException: Unable to query block by hash abcd236db83282f37020778c5e99b6ebc6ce609624ba391e9adc5b72207e39fe 
.... for channel mychannel from peer peer0.org1.example.com 
    with message Sending proposal to peer0.org1.example.com failed because of: gRPC failure=Status{code=UNKNOWN, description=chaincode error (status: 500, message: Failed to get block hash ��#m�2��p w�^�����`�$�9��[r ~9�, error Entry not found in index), cause=null}
	at org.hyperledger.fabric.sdk.Channel.queryBlockByHash(Channel.java:1559)
	... 24 more

```

**Comment by JeetenJaiswal** [comment]
Issue resolved with PR #20
